language: python

cache:
  - pip
  - ccache

matrix:
  include:
    - os: linux
      python: "3.6"

install:
  - pip3 install -U pip wheel
  - pip3 install numpy
    # NOTE: use 1.0.1 for travis check because 1.1.0 > argmax behavior is strange
  - pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl
  - pip3 install torchvision==0.2.2
  - pip3 install -e .
  - pip3 install -e .[test]

script:
  - flake8 wavenet_vocoder test
  - autopep8 -r wavenet_vocoder test --exclude wavenet_vocoder/utils --global-config .pep8 --diff --max-line-length 120 | tee check_autopep8
  - test ! -s check_autopep8
  - pytest

sudo: false

addons:
  apt:
    packages:
      - cmake
      - python3-dev
